spring.application.name=batch-jsr353

spring.datasource.url=jdbc:db2://localhost:50000/testdb
spring.datasource.username=db2inst1
spring.datasource.password=test123
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver

spring.batch.jdbc.initialize-schema=always

# when this is true SpringBoot will run all the jobs it finds configured
# either in java configuration classes like HelloWorldJobConfig or in xml job files
# spring.batch.job.enabled = false;