spring.application.name=batch-test

# use embedded h2 database as Batch Metadata for this basic test
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=postgres
# not needed - SpringBoot peaks it up 
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.batch.jdbc.initialize-schema=always

# Auto-configuration for Spring Batch. If a single job is found in the context, it will be executed on startup.
# Disable this behavior with spring.batch.job.enabled=false.
# Note that if there are multiple jobs defined as @Component or in any other way
# and this is not specifically set to false an exception will be thrown.  
spring.batch.job.enabled=false;
